services:
  postgres:
    image: postgres:16
    container_name: p11-postgres
    command: ["postgres", "-c", "wal_level=logical", "-c", "max_replication_slots=10", "-c", "max_wal_senders=10"]
    ports:
      - "${POSTGRES_PORT:-5437}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-nuvemstore}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../00-modelagem-transacional/ddl/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-nuvemstore}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: p11-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092
    ports:
      - "${REDPANDA_BROKER_PORT:-9092}:9092"

  connect:
    image: debezium/connect:2.7
    container_name: p11-connect
    depends_on:
      - redpanda
      - postgres
    ports:
      - "${CONNECT_PORT:-8083}:8083"
    environment:
      BOOTSTRAP_SERVERS: redpanda:9092
      GROUP_ID: debezium-connect
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

  console:
    image: redpandadata/console:latest
    container_name: p11-console
    depends_on:
      - redpanda
    ports:
      - "${REDPANDA_CONSOLE_PORT:-8080}:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092

volumes:
  postgres-data:
