services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: p12-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092
    ports:
      - "${REDPANDA_BROKER_PORT:-9092}:9092"

  console:
    image: redpandadata/console:latest
    container_name: p12-console
    depends_on:
      - redpanda
    ports:
      - "${REDPANDA_CONSOLE_PORT:-8080}:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
