services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: p08-namenode
    environment:
      CLUSTER_NAME: nuvemstore
    ports:
      - "${HDFS_NAMENODE_PORT:-9870}:9870"
    volumes:
      - hdfs-name:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: p08-datanode
    depends_on:
      - namenode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    volumes:
      - hdfs-data:/hadoop/dfs/data

  spark-master:
    image: bitnami/spark:3.5
    container_name: p08-spark-master
    environment:
      SPARK_MODE: master
    ports:
      - "${SPARK_MASTER_UI_PORT:-8090}:8080"
      - "${SPARK_MASTER_PORT:-7077}:7077"
    volumes:
      - ./spark/jobs:/jobs

  spark-worker:
    image: bitnami/spark:3.5
    container_name: p08-spark-worker
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
    volumes:
      - ./spark/jobs:/jobs

  hive-metastore:
    image: apache/hive:4.0.0
    container_name: p08-hive-metastore
    ports:
      - "${HIVE_METASTORE_PORT:-9083}:9083"
    environment:
      SERVICE_NAME: metastore
    volumes:
      - metastore-data:/opt/hive/data

volumes:
  hdfs-name:
  hdfs-data:
  metastore-data:
